name: Bug Report
description: File a bug report
title: '[Bug]: '
labels:
  - bug
assignees: null
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Summary
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
      value: A bug happened!
    validations:
      required: true
  - type: textarea
    id: problem-area
    attributes:
      label: Problem area
      description: >-
        Please link the pull request or commit corresponding to the behaviour
        described in the bug report.
      validations:
        required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: >-
        Describe the environment(s) in which the bug occurs, including both
        build and runtime environments, where relevant.
      validations:
        required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: >
        1. Go to '...' 

        2. Tap on '....'

        3. Scroll down to '....'

        4. See error


        If applicable, add screenshots to help explain your problem. All
        screenshots must be resized so that they display at a comfortable size
        for viewing.
      validations:
        required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what you expected to happen.
      validations:
        required: false
  - type: textarea
    id: extra
    attributes:
      label: Additional Information
      description: Any additional information about the problem that might be relevant.
      validations:
        required: false
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: >-
        Describe potential approaches for mitigating or resolving the problem,
        and suggest directions for future investigation in the absence of
        obvious solutions. Discuss any partial solutions or unsuccessful
        approaches that have been tested so far.
      validations:
        required: false
