require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

# MapLibre configuration for React Native Mapbox GL
# TODO Use only after https://github.com/react-native-mapbox-gl/maps/pull/1571#issuecomment-1003716382 is addressed
#$RNMBGL_Use_SPM = true
#$RNMGL_USE_MAPLIBRE = true

target 'MapboxGeometryEditorExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'MapboxGeometryEditorExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  pre_install do |installer|
    $RNMBGL.pre_install(installer)
  end

  post_install do |installer|
    react_native_post_install(installer)
    $RNMBGL.post_install(installer)
  end
end